### ISSUE TITLE
No Stream Available even when the latest version of the plugin offers functional streams under Kodi

### ISSUE THREAD

**Issue by HalosGhost** [cthlo/exoduscli#1]
It seems no matter what I try, `exoduscli` returns "No Stream Available" after checking a few providers.

Is this just an update needed to the plugin? I attempted to copy the newest version of the plugin and the URL resolver into `exoduscli`'s directory, but it did not appear to change the result.

**Comment by cthlo** [comment]
Thanks! Looking at it.
Which version did you replace it with?
Could you also try removing `exoduscli/fakexbmc/special` ?

(It's (exodus-1.3.0) not listing any movies for me on a fresh clone, so I'll need to update the addon.)

**Comment by HalosGhost** [comment]
After removing that directory, it appears to return "No Stream Available" immediately rather than checking a few providers and then throwing the message.

The version of Exodus I am testing with is 1.3.7

**Comment by cthlo** [comment]
Interesting, because that's where the caches are stored. I would expect it to try searching for the streams again.
Are you running it directly with `python2` or from `pip` installation?

What's happening for me (at time of comment) upon fresh clone, running with `python2 -m exoduscli.main`:
- No movie listing (e.g. Movies > Genres > Action shows nothing)
- 'People Watching' is still listing movies though
- Search still works (e.g. Searched for 'thor', choosing option 1: 'Thor (2011)' gives 25 stream options)

**Comment by HalosGhost** [comment]
Indeed, the movie listing example you gave also does not work for me.

Search still works, but when I select an episode to watch, I get "No Stream Available".

To answer your question, I suppose I am running it from `python2` (I preliminarily packaged it for ArchLinux so it is installed to my system, not in my home directory, but I did not use `pip`).

**Comment by cthlo** [comment]
I see. Would you mind sharing which episode you're trying to get streams for? I just want to make sure I can reproduce.

**Comment by HalosGhost** [comment]
I've tried various ones. So far, it looks like anything from _Star Trek Voyager_ to _Last Week Tonight_ to _Andromeda_ to really anything.

Any chance you are on Freenode and would have a second to chat?

**Comment by cthlo** [comment]
Weirdly, it is showing 70 streams for _Star Trek Voyager_ s1e1 on mine. In any case, I'll need to update Exodus to >2 because 1.3.7 doesn't seem to be listing movies on Kodi.

(I've started a channel on Freenode #exoduscli)
